[project]
name = "repl-nix-stockinsighttracker"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.2.3",
    "plotly>=5.24.1",
    "streamlit==1.40.1",
    "ta>=0.11.0",
    "yfinance>=0.2.49",
]
