[server]
headless = true
enableCORS = true
enableXsrfProtection = false
address = "0.0.0.0"
port = 5000

[theme]
primaryColor = "#0031f6"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
